# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backup.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62\x61\x63kup.proto\x12\x06\x62\x61\x63kup\"8\n\x13StoreMessageRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\'\n\x14StoreMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x17\n\x15GetAllMessagesRequest\"E\n\x16GetAllMessagesResponse\x12+\n\ruser_messages\x18\x01 \x03(\x0b\x32\x14.backup.UserMessages\"2\n\x0cUserMessages\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08messages\x18\x02 \x03(\t2\xab\x01\n\rBackupService\x12I\n\x0cStoreMessage\x12\x1b.backup.StoreMessageRequest\x1a\x1c.backup.StoreMessageResponse\x12O\n\x0eGetAllMessages\x12\x1d.backup.GetAllMessagesRequest\x1a\x1e.backup.GetAllMessagesResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backup_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STOREMESSAGEREQUEST._serialized_start=24
  _STOREMESSAGEREQUEST._serialized_end=80
  _STOREMESSAGERESPONSE._serialized_start=82
  _STOREMESSAGERESPONSE._serialized_end=121
  _GETALLMESSAGESREQUEST._serialized_start=123
  _GETALLMESSAGESREQUEST._serialized_end=146
  _GETALLMESSAGESRESPONSE._serialized_start=148
  _GETALLMESSAGESRESPONSE._serialized_end=217
  _USERMESSAGES._serialized_start=219
  _USERMESSAGES._serialized_end=269
  _BACKUPSERVICE._serialized_start=272
  _BACKUPSERVICE._serialized_end=443
# @@protoc_insertion_point(module_scope)
