# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import backup_pb2 as backup__pb2


class BackupServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreMessageHistory = channel.unary_unary(
                '/backup.BackupService/StoreMessageHistory',
                request_serializer=backup__pb2.StoreMessageHistoryRequest.SerializeToString,
                response_deserializer=backup__pb2.StoreMessageHistoryResponse.FromString,
                )
        self.GetAllMessageHistory = channel.unary_unary(
                '/backup.BackupService/GetAllMessageHistory',
                request_serializer=backup__pb2.GetAllMessageHistoryRequest.SerializeToString,
                response_deserializer=backup__pb2.GetAllMessageHistoryResponse.FromString,
                )


class BackupServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StoreMessageHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllMessageHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BackupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreMessageHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreMessageHistory,
                    request_deserializer=backup__pb2.StoreMessageHistoryRequest.FromString,
                    response_serializer=backup__pb2.StoreMessageHistoryResponse.SerializeToString,
            ),
            'GetAllMessageHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllMessageHistory,
                    request_deserializer=backup__pb2.GetAllMessageHistoryRequest.FromString,
                    response_serializer=backup__pb2.GetAllMessageHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'backup.BackupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BackupService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreMessageHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/backup.BackupService/StoreMessageHistory',
            backup__pb2.StoreMessageHistoryRequest.SerializeToString,
            backup__pb2.StoreMessageHistoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllMessageHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/backup.BackupService/GetAllMessageHistory',
            backup__pb2.GetAllMessageHistoryRequest.SerializeToString,
            backup__pb2.GetAllMessageHistoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
